### ISSUE TITLE
Encoding error when sending numbers

### ISSUE THREAD

**Issue by scaramagus** [fisadev/grillo#2]
Trying to send a string of integers results in the following error:
```
$ grillo text "123456"
Traceback (most recent call last):
  File "/home/agustin/code/pycamp2019/grillo/env/bin/grillo", line 11, in <module>
    load_entry_point('Grillo', 'console_scripts', 'grillo')()
  File "/home/agustin/code/pycamp2019/grillo/grillo/grillo.py", line 235, in main
    fire.Fire(GrilloCli)
  File "/home/agustin/code/pycamp2019/grillo/env/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/agustin/code/pycamp2019/grillo/env/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/agustin/code/pycamp2019/grillo/env/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/agustin/code/pycamp2019/grillo/grillo/grillo.py", line 190, in text
    grillo.send_text(text)
  File "/home/agustin/code/pycamp2019/grillo/grillo/grillo.py", line 95, in send_text
    self.send_message(MessageKind.TEXT, text.encode("utf-8"))
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by fisadev** [comment]
fixed :)
